#!/bin/bash
# URL-Params 双向联动功能演示脚本

echo "=========================================="
echo "Issue #11: URL-Params 双向联动演示"
echo "=========================================="
echo ""
echo "1. 启动应用 (已构建完成)"
echo "   ./build/macos/Build/Products/Release/hopp.app/Contents/MacOS/hopp --test-mode"
echo ""
echo "2. 运行 UI 测试"
echo "   python3 integration_test/test_url_params_sync.py"
echo ""
echo "3. 或使用命令行逐步测试:"
echo "   python3 integration_test/test_client.py create_request"
echo "   python3 integration_test/test_client.py set_url --url 'https://httpbin.org/get?name=test&page=1'"
echo "   python3 integration_test/test_client.py switch_request_tab --tab params"
echo "   python3 integration_test/test_client.py verify_url_params_sync"
echo ""
echo "功能说明:"
echo "   - 在 URL 输入 ?key=value 时，Params Tab 自动同步显示"
echo "   - 在 Params Tab 添加/修改/删除参数时，URL 自动更新"
echo "   - 支持 URL 编码/解码、特殊字符处理"
echo ""
echo "单元测试:"
echo "   fvm flutter test test/utils/url_params_sync_test.dart"
echo ""
